plugins:
  discourse_tura_list:
    type: list
    default: "tba==The Blue Alliance, a site for FIRST Robotics Competition event data|frc==FIRST Robotics Competition|ftc==FIRST Tech Challenge|vrc==VEX Robotics Competition|wcp==West Coast Products|am==AndyMark|pdp==CTRE's Power Distribution Panel|pdh==REV's Power Distribution Hub|vrm==Voltage Regulator Module|rpm==Revolutions Per Minute|ttb==The Thrifty Bot|ppr==Pulses Per Revolution|epa==Expected Points Added|pwm==Pulse Width Modulation|kop==Kit of Parts|ll==Limelight, an integrated vision coprocessor|rpi==Raspberry Pi|pv==Photon Vision, an open source vision library for coprocessors|cots==Commercial, off-the-shelf|fms==Field Management System"
    client: true
  discourse_tura_enabled:
    type: boolean
    default: true
    client: true
